apiVersion: v1
kind: Secret
metadata:
  name: longhorn-auth
  namespace: longhorn-system
type: Opaque
data:
  users: QWRtaW46JGFwcjEkVVJqSUNVR2kkUHB3dXY0bDh5NmQ5WlZDWmZLLzl6MQo=  # TODO: Update with actual credentials
