apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: monitoring
data:
  traefik.yaml:
    api:
      dashboard: true
      insecure: false

    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        address: ":443"
      metrics:
        address: ":8082"

    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        allowExternalNameServices: true

    metrics:
      prometheus:
        entryPoint: metrics
        addEntryPointsLabels: true
        addServicesLabels: true

    accessLog:
      filePath: "/data/access.log"
      bufferingSize: 100

    pilot:
      enabled: false
