apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth
  namespace: monitoring
type: Opaque
data:
  users: |2
    YWRtaW46JGFwcjEkVnJ0UE5LTFYkNHBJeEVEV2JqNHp1NS8zNVRnY1VHMS8K  # admin:admin (change this!)
